name: Caller CI

on:
  workflow_dispatch:

permissions: write-all

jobs:
  print-outputs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PS script
        id: test
        run: |
          flag=false
          FOLDER="${{ github.workspace }}\\result"
          if [ ! -e $FOLDER ]; then
              $flag=true
              echo "::set-output name=result::$flag"
          else 
              echo "::set-output name=result::$flag"
          fi
        shell: bash
      - name: check flag
        run: |
          echo ${{ steps.test.outputs.result }}
#       - name: Parse HTML report
#         uses: harisyammnv/Action-html-parser@v0.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           html_file: "result/index.html"
#       - run: |
#           cd .github
#           ls -lrt
#       - uses: ./.github/actions
#         with:
#           who-to-greet: "Hari the Octocat"
#       - run: echo random-number ${{ steps.foo.outputs.random-number }}
#         shell: bash
