name: Caller CI

on:
  workflow_dispatch:

jobs:
  call-template-workflow:
    uses: harisyammnv/reusable-workflows/.github/workflows/template.yaml@master
    with:
      project_name: Temp-Project
      model_name: Temp-Model
  summary:
    runs-on: ubuntu-latest
    needs: call-template-workflow
    steps:
      - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
    
