name: Caller CI

on:
  workflow_dispatch:

permissions: write-all

jobs:
  print-outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#       - name: Parse HTML report
#         uses: harisyammnv/Action-html-parser@v0.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           html_file: "result/index.html"
      - run: pwd
      - run: ls -lrt
      - uses: ./composite-actions/test.yml
        with:
          who-to-greet: "Hari the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
