name: Caller CI

on:
  workflow_dispatch:

jobs:
  #call-template-workflow:
  gets-outputs:
    runs-on: windows-latest
    steps:
    - name: Run Job
      uses: harisyammnv/reusable-workflows@master
      with:
        project_name: Temp-Project
        model_name: Temp-Model
  print-outputs:
      runs-on: ubuntu-latest
      needs: gets-outputs
      steps:
      - name: Print Job Artifact
        run: |
          echo "### Hello world! :rocket: The Artifact URL: [Link](${{needs.gets-outputs.outputs.artifact_url}})" >> $GITHUB_STEP_SUMMARY
