name: Caller CI

on:
  workflow_dispatch:

jobs:
  print-outputs:
      runs-on: windows-latest
      steps:
        - name: Parse HTML report
          uses: harisyammnv/html-parser@development
          with:
            html_file: "result/index.html"
