name: Caller CI

on:
  workflow_dispatch:
  
permissions: write-all

jobs:
  print-outputs:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Parse HTML report
          uses: harisyammnv/html-parser@development
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            html_file: "result/index.html"
