name: Reusable CI Template

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      model_name:
        required: true
        type: string

env:
  project_name: ${{ inputs.project_name }}
  model_name: '${{ inputs.model_name }}'

jobs:
  testPS:
    name: Pass Inputs and Print out
    runs-on: windows-latest
    #Write-Host "[INFO] This is an info statement: " -NoNewline
    #Write-Host $str_url
    outputs:
      output1: ${{ steps.step1.outputs.artifact_url }}
    steps:
      - name: PowerShell print statement
        id: step1
        run: |
          Write-Output "Project Name: .\$env:project_name-Code.zip"
          Write-Output $env:model_name
          $str_url = "https://artifactory.avl.com/artifactory/pypi-test/avl-py-doc-base/0.1.2/avl_py_doc_base-0.1.2.tar.gz"
          echo "::set-output name=artifact_url::$str_url"
  #jobArtifacts:
  #  runs-on: ubuntu-latest
  #  needs: testPS
  #  steps:
  #    - name: Job Artifact
  #      run: |
  #        echo "### Hello world! :rocket: The Artifact URL: [Link](${{needs.testPS.outputs.output1}})" >> $GITHUB_STEP_SUMMARY
